// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqcrlmwwfrmudioacwpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxY3JsbXd3ZnJtdWRpb2Fjd3BkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NDUxMTQsImV4cCI6MjA3MjIyMTExNH0.Y58vMvc4J58Y61rBvBHBjtw6bAYKHCrt3jx5wXlt1gU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});